### ISSUE TITLE
Crash upon loading some maps: Array Index out of bounds 

### ISSUE THREAD

**Issue by sneakernets** [ioan-chera/AutoDoom#1]
On some occasions, loading MAP01 of BTSX Episode 1 causes AutoDoom to crash to command prompt with an "Array index out of bounds" error. It's not readily reproducible; but it can be triggered by loading the map several times or running another instance and trying there.

I'll post more information as I find them, and what specific wads cause this issue.

**Comment by ioan-chera** [comment]
Do you have the exact WAD that had this? Unfortunately there have been a ton of updates to that megawad and it's best if I get the exact one.

**Comment by ioan-chera** [comment]
Fixed for now. Was caused by singularities (0-length splits) in the node building process.
