### ISSUE TITLE
Memory Leak

### ISSUE THREAD

**Issue by sneakernets** [ioan-chera/AutoDoom#14]
I discovered this while testing AutoDoom on the Pandora's Box PocketPC. I let it run for a few hours, and came back to see the process triggered the auto kill function - the system ran out of memory completely. Every crash I've witnessed is usually after the bot has died several dozen times in the same map.

**Comment by ioan-chera** [comment]
Fixed the main culprit. Probably no other leaks occur now.

**Comment by sneakernets** [comment]
Awesome.
