### ISSUE TITLE
Cache already-built nodes if bot replays map in Singleplayer

### ISSUE THREAD

**Issue by sneakernets** [ioan-chera/AutoDoom#2]
AutoDoom currently rebuilds the GL nodes upon each level load, which may be unnecessary, if the bot dies and presses spacebar afterwards. This is only an issue in Single player mode.

**Comment by ioan-chera** [comment]
Bot map (including GL nodes) now gets cached so there'll be less delay when reloading the map. I'll close this issue when I'm sure it runs without bugs.

**Comment by sneakernets** [comment]
Glad to hear there's progress on this. :+1:

**Comment by ioan-chera** [comment]
No problems observer; issue closed.
