### ISSUE TITLE
Build Error Eternity.exe 32 and 64 bit

### ISSUE THREAD

**Issue by Quiddy85** [ioan-chera/AutoDoom#27]
I grabbed the latest build from here and I get a build error I have the output for you to look at

1>------ Build started: Project: zlib, Configuration: Release x64 ------
2>------ Build started: Project: snes_spc, Configuration: Release x64 ------
3>------ Build started: Project: ACSVM, Configuration: Release x64 ------
2>dsp.cpp
1>adler32.c
2>SNES_SPC.cpp
1>compress.c
1>crc32.c
2>SNES_SPC_misc.cpp
1>deflate.c
1>gzclose.c
2>SNES_SPC_state.cpp
1>gzlib.c
2>spc.cpp
1>gzread.c
2>SPC_DSP.cpp
1>gzwrite.c
2>..\snes_spc\SPC_DSP.cpp(164): warning C4146: unary minus operator applied to unsigned type, result still unsigned
2>SPC_Filter.cpp
2>Generating Code...
3>Action.cpp
3>Array.cpp
1>infback.c
3>BinaryIO.cpp
1>inffast.c
1>inflate.c
1>inftrees.c
1>trees.c
1>uncompr.c
1>zutil.c
3>CallFunc.cpp
3>CodeData.cpp
3>Environment.cpp
2>..\snes_spc\snes_spc.def(2): warning LNK4017: DESCRIPTION statement not supported for the target platform; ignored
2>   Creating library C:\Users\quidd\Desktop\AutoDoom-AutoDoom\vc2017\x64\Release\snes_spc.lib and object C:\Users\quidd\Desktop\AutoDoom-AutoDoom\vc2017\x64\Release\snes_spc.exp
1>zlib.vcxproj -> C:\Users\quidd\Desktop\AutoDoom-AutoDoom\vc2017\x64\Release\zlib.lib
4>------ Build started: Project: libpng, Configuration: Release x64 ------
3>Error.cpp
4>png.c
2>snes_spc.vcxproj -> C:\Users\quidd\Desktop\AutoDoom-AutoDoom\vc2017\x64\Release\snes_spc.dll
2>Done building project "snes_spc.vcxproj".
3>Function.cpp
3>Init.cpp
4>pngerror.c
3>Jump.cpp
4>pngget.c
4>pngmem.c
3>Module.cpp
4>pngpread.c
3>ModuleACS0.cpp
4>pngread.c
3>ModuleACSE.cpp
4>pngrio.c
4>pngrtran.c
3>PrintBuf.cpp
4>pngrutil.c
3>Scope.cpp
4>pngset.c
4>pngtrans.c
3>Script.cpp
4>pngwio.c
3>Serial.cpp
4>pngwrite.c
4>pngwtran.c
3>String.cpp
4>pngwutil.c
3>Thread.cpp
3>ThreadExec.cpp
4>libpng.vcxproj -> C:\Users\quidd\Desktop\AutoDoom-AutoDoom\vc2017\x64\Release\libpng.lib
3>Compiling...
3>Tracer.cpp
3>ACSVM.vcxproj -> C:\Users\quidd\Desktop\AutoDoom-AutoDoom\vc2017\x64\Release\ACSVM.lib
5>------ Build started: Project: Eternity, Configuration: Release x64 ------
5>64 bit Processing ..\midiproc\midiproc.idl
5>midiproc.idl
5>cl : Command line warning D9002: ignoring unknown option '/arch:SSE2'
5>cl : Command line warning D9002: ignoring unknown option '/arch:SSE2'
5>acs_func.cpp
5>cl : Command line warning D9002: ignoring unknown option '/arch:SSE2'
5>acs_intr.cpp
5>cl : Command line warning D9002: ignoring unknown option '/arch:SSE2'
5>am_color.cpp
5>cl : Command line warning D9002: ignoring unknown option '/arch:SSE2'
5>am_map.cpp
5>am_svg.cpp
5>b_analysis.cpp
5>b_ape.cpp
5>b_botmap.cpp
5>b_botmaptemp.cpp
5>b_compression.cpp
5>b_glbsp.cpp
5>b_itemlearn.cpp
5>b_lineeffect.cpp
5>b_msector.cpp
5>b_path.cpp
5>b_statistics.cpp
5>b_think.cpp
5>b_trace.cpp
5>b_util.cpp
5>cam_aim.cpp
5>..\source\autodoom\b_trace.cpp(596): warning C4805: '&': unsafe mix of type 'unsigned int' and type 'bool' in operation
5>cam_common.cpp
5>cam_shoot.cpp
5>cam_use.cpp
5>c_batch.cpp
5>c_cmd.cpp
5>c_io.cpp
5>c_net.cpp
5>c_runcmd.cpp
5>..\Source\c_net.cpp(232): warning C4101: 'command': unreferenced local variable
5>confuse.cpp
5>lexer.cpp
5>d_deh.cpp
5>d_dehtbl.cpp
5>d_diskfile.cpp
5>d_files.cpp
5>d_findiwads.cpp
5>d_gi.cpp
5>d_io.cpp
5>d_items.cpp
5>d_iwad.cpp
5>d_main.cpp
5>d_net.cpp
5>doomdef.cpp
5>doomstat.cpp
5>dstrings.cpp
5>ev_sectors.cpp
5>e_anim.cpp
5>e_args.cpp
5>e_cmd.cpp
5>e_dstate.cpp
5>e_edf.cpp
5>e_edfmetatable.cpp
5>e_exdata.cpp
5>e_fonts.cpp
5>e_gameprops.cpp
5>e_hash.cpp
5>e_inventory.cpp
5>e_lib.cpp
5>e_mod.cpp
5>e_player.cpp
5>e_puff.cpp
5>e_reverbs.cpp
5>e_rtti.cpp
5>e_sound.cpp
5>e_sprite.cpp
5>e_states.cpp
5>e_string.cpp
5>e_switch.cpp
5>e_things.cpp
5>e_ttypes.cpp
5>e_udmf.cpp
5>e_weapons.cpp
5>f_finale.cpp
5>f_wipe.cpp
5>g_bind.cpp
5>g_cmd.cpp
5>g_demolog.cpp
5>g_dmflag.cpp
5>g_game.cpp
5>g_gfs.cpp
5>i_directory.cpp
5>i_timer.cpp
5>hu_frags.cpp
5>hu_over.cpp
5>hu_stuff.cpp
5>hi_stuff.cpp
5>in_lude.cpp
5>mn_items.cpp
5>m_utils.cpp
5>p_portalblockmap.cpp
5>p_portalclip.cpp
5>p_portalcross.cpp
5>i_sdltimer.cpp
5>s_formats.cpp
5>s_musinfo.cpp
5>s_reverb.cpp
5>v_image.cpp
5>wi_stuff.cpp
5>m_argv.cpp
5>m_bbox.cpp
5>m_buffer.cpp
5>m_cheat.cpp
5>m_fcvt.cpp
5>m_hash.cpp
5>m_misc.cpp
5>m_qstr.cpp
5>m_queue.cpp
5>m_random.cpp
5>m_shots.cpp
5>m_strcasestr.cpp
5>m_syscfg.cpp
5>..\Source\m_random.cpp(198): warning C4101: 'i': unreferenced local variable
5>m_vector.cpp
5>mn_emenu.cpp
5>mn_engin.cpp
5>mn_files.cpp
5>mn_htic.cpp
5>mn_menus.cpp
5>mn_misc.cpp
5>mn_skinv.cpp
5>p_anim.cpp
5>p_ceilng.cpp
5>p_chase.cpp
5>p_cmd.cpp
5>p_doors.cpp
5>p_enemy.cpp
5>p_floor.cpp
5>p_genlin.cpp
5>p_hubs.cpp
5>p_info.cpp
5>p_inter.cpp
5>p_lights.cpp
5>p_map.cpp
5>p_map3d.cpp
5>p_maputl.cpp
5>p_mobj.cpp
5>p_mobjcol.cpp
5>p_partcl.cpp
5>p_plats.cpp
5>p_portal.cpp
5>p_pushers.cpp
5>p_saveg.cpp
5>p_scroll.cpp
5>p_sector.cpp
5>p_setup.cpp
5>p_sight.cpp
5>p_skin.cpp
5>p_slopes.cpp
5>p_spec.cpp
5>p_switch.cpp
5>p_telept.cpp
5>p_things.cpp
5>p_tick.cpp
5>p_trace.cpp
5>p_user.cpp
5>p_xenemy.cpp
5>polyobj.cpp
5>r_bsp.cpp
5>r_data.cpp
5>r_draw.cpp
5>r_drawq.cpp
5>r_dynabsp.cpp
5>r_dynseg.cpp
5>r_main.cpp
5>r_plane.cpp
5>r_portal.cpp
5>r_ripple.cpp
5>r_segs.cpp
5>r_sky.cpp
5>r_span.cpp
5>r_textur.cpp
5>r_things.cpp
5>r_voxels.cpp
5>s_sndseq.cpp
5>s_sound.cpp
5>sounds.cpp
5>i_exception.cpp
5>i_fnames.cpp
5>i_input.cpp
5>i_main.cpp
5>i_midirpc.cpp
5>i_net.cpp
5>i_opndir.cpp
5>C:\Program Files (x86)\Microsoft SDKs\Windows\v7.1A\include\winsock.h(304): warning C4005: 'INADDR_ANY': macro redefinition (compiling source file ..\Source\sdl\i_main.cpp)
5>C:\Libs\SDL2_net-2.0.1\include\SDL_net.h(102): note: see previous definition of 'INADDR_ANY' (compiling source file ..\Source\sdl\i_main.cpp)
5>C:\Program Files (x86)\Microsoft SDKs\Windows\v7.1A\include\winsock.h(306): warning C4005: 'INADDR_BROADCAST': macro redefinition (compiling source file ..\Source\sdl\i_main.cpp)
5>C:\Libs\SDL2_net-2.0.1\include\SDL_net.h(111): note: see previous definition of 'INADDR_BROADCAST' (compiling source file ..\Source\sdl\i_main.cpp)
5>C:\Program Files (x86)\Microsoft SDKs\Windows\v7.1A\include\winsock.h(307): warning C4005: 'INADDR_NONE': macro redefinition (compiling source file ..\Source\sdl\i_main.cpp)
5>C:\Libs\SDL2_net-2.0.1\include\SDL_net.h(105): note: see previous definition of 'INADDR_NONE' (compiling source file ..\Source\sdl\i_main.cpp)
5>i_pcsound.cpp
5>i_picker.cpp
5>i_sdlgamepads.cpp
5>i_sdlgl2d.cpp
5>i_sdlmusic.cpp
5>i_sdlsound.cpp
5>i_sdlvideo.cpp
5>i_sound.cpp
5>i_system.cpp
5>i_w32main.cpp
5>mmus2mid.cpp
5>ser_main.cpp
5>st_hbar.cpp
5>st_lib.cpp
5>st_stuff.cpp
5>v_alloc.cpp
5>..\Source\st_hbar.cpp(86): warning C4267: '-=': conversion from 'size_t' to 'int', possible loss of data
5>v_block.cpp
5>v_buffer.cpp
5>v_font.cpp
5>v_misc.cpp
5>v_patch.cpp
5>v_patchfmt.cpp
5>v_png.cpp
5>v_video.cpp
5>w_formats.cpp
5>w_hacks.cpp
5>w_levels.cpp
5>w_wad.cpp
5>w_zip.cpp
5>xl_animdefs.cpp
5>xl_emapinfo.cpp
5>xl_mapinfo.cpp
5>xl_musinfo.cpp
5>xl_sndinfo.cpp
5>xl_umapinfo.cpp
5>z_native.cpp
5>info.cpp
5>psnprntf.cpp
5>tables.cpp
5>version.cpp
5>a_common.cpp
5>a_counters.cpp
5>a_decorate.cpp
5>a_doom.cpp
5>a_general.cpp
5>a_heretic.cpp
5>a_hexen.cpp
5>xl_scripts.cpp
5>i_gamepads.cpp
5>i_platform.cpp
5>i_video.cpp
5>gl_init.cpp
5>gl_primitives.cpp
5>gl_projection.cpp
5>gl_texture.cpp
5>gl_vars.cpp
5>metaapi.cpp
5>metaqstring.cpp
5>cam_sight.cpp
5>ev_actions.cpp
5>..\source\metaapi.cpp(86): warning C4267: '-=': conversion from 'size_t' to 'uint32_t', possible loss of data
5>ev_bindings.cpp
5>ev_specials.cpp
5>ev_static.cpp
5>t_plane.cpp
5>i_xinput.cpp
5>cl : Command line warning D9002: ignoring unknown option '/arch:SSE2'
5>cl : Command line warning D9002: ignoring unknown option '/arch:SSE2'
5>analyze.c
5>cl : Command line warning D9002: ignoring unknown option '/arch:SSE2'
5>blockmap.c
5>cl : Command line warning D9002: ignoring unknown option '/arch:SSE2'
5>glbsp.c
5>cl : Command line warning D9002: ignoring unknown option '/arch:SSE2'
5>level.c
5>node.c
5>reject.c
5>seg.c
5>system.c
5>util.c
5>wad.c
5>txt_button.c
5>txt_checkbox.c
5>txt_conditional.c
5>txt_desktop.c
5>txt_dropdown.c
5>txt_fileselect.c
5>txt_gui.c
5>txt_inputbox.c
5>txt_io.c
5>txt_label.c
5>txt_radiobutton.c
5>txt_scrollpane.c
5>txt_sdl.c
5>txt_separator.c
5>txt_spinctrl.c
5>txt_strut.c
5>txt_table.c
5>txt_utf8.c
5>txt_widget.c
5>txt_window.c
5>txt_window_action.c
5>midiproc_c.c
5>cl : Command line warning D9002: ignoring unknown option '/arch:SSE2'
5>p_pspr.cpp
5>..\Source\p_pspr.cpp(1160): warning C4101: 'i': unreferenced local variable
5>   Creating library C:\Users\quidd\Desktop\AutoDoom-AutoDoom\vc2017\x64\Release\Eternity.lib and object C:\Users\quidd\Desktop\AutoDoom-AutoDoom\vc2017\x64\Release\Eternity.exp
5>b_analysis.obj : error LNK2001: unresolved external symbol "void __cdecl A_FireCGun(struct actionargs_t *)" (?A_FireCGun@@YAXPEAUactionargs_t@@@Z)
5>b_analysis.obj : error LNK2001: unresolved external symbol "void __cdecl A_CloseShotgun2(struct actionargs_t *)" (?A_CloseShotgun2@@YAXPEAUactionargs_t@@@Z)
5>b_analysis.obj : error LNK2001: unresolved external symbol "void __cdecl A_FireBFG(struct actionargs_t *)" (?A_FireBFG@@YAXPEAUactionargs_t@@@Z)
5>b_analysis.obj : error LNK2001: unresolved external symbol "void __cdecl A_Saw(struct actionargs_t *)" (?A_Saw@@YAXPEAUactionargs_t@@@Z)
5>b_analysis.obj : error LNK2001: unresolved external symbol "void __cdecl A_FireOldBFG(struct actionargs_t *)" (?A_FireOldBFG@@YAXPEAUactionargs_t@@@Z)
5>b_analysis.obj : error LNK2001: unresolved external symbol "void __cdecl A_FireShotgun2(struct actionargs_t *)" (?A_FireShotgun2@@YAXPEAUactionargs_t@@@Z)
5>b_analysis.obj : error LNK2001: unresolved external symbol "void __cdecl A_Punch(struct actionargs_t *)" (?A_Punch@@YAXPEAUactionargs_t@@@Z)
5>b_analysis.obj : error LNK2001: unresolved external symbol "void __cdecl A_FirePistol(struct actionargs_t *)" (?A_FirePistol@@YAXPEAUactionargs_t@@@Z)
5>b_analysis.obj : error LNK2001: unresolved external symbol "void __cdecl A_BFGBurst(struct actionargs_t *)" (?A_BFGBurst@@YAXPEAUactionargs_t@@@Z)
5>b_analysis.obj : error LNK2001: unresolved external symbol "void __cdecl A_BFGSpray(struct actionargs_t *)" (?A_BFGSpray@@YAXPEAUactionargs_t@@@Z)
5>b_analysis.obj : error LNK2001: unresolved external symbol "void __cdecl A_BFG11KHit(struct actionargs_t *)" (?A_BFG11KHit@@YAXPEAUactionargs_t@@@Z)
5>b_analysis.obj : error LNK2001: unresolved external symbol "void __cdecl A_BouncingBFG(struct actionargs_t *)" (?A_BouncingBFG@@YAXPEAUactionargs_t@@@Z)
5>b_analysis.obj : error LNK2001: unresolved external symbol "void __cdecl A_FireMissile(struct actionargs_t *)" (?A_FireMissile@@YAXPEAUactionargs_t@@@Z)
5>b_analysis.obj : error LNK2001: unresolved external symbol "void __cdecl A_FireShotgun(struct actionargs_t *)" (?A_FireShotgun@@YAXPEAUactionargs_t@@@Z)
5>b_analysis.obj : error LNK2001: unresolved external symbol "void __cdecl A_FirePlasma(struct actionargs_t *)" (?A_FirePlasma@@YAXPEAUactionargs_t@@@Z)
5>b_think.obj : error LNK2001: unresolved external symbol "char const * __cdecl VOC_IndefiniteArticle(char const *)" (?VOC_IndefiniteArticle@@YAPEBDPEBD@Z)
5>b_think.obj : error LNK2001: unresolved external symbol "void __cdecl VOC_AddSpaces(class qstring &)" (?VOC_AddSpaces@@YAXAEAVqstring@@@Z)
5>d_dehtbl.obj : error LNK2001: unresolved external symbol "void __cdecl A_StaffAttackPL2(struct actionargs_t *)" (?A_StaffAttackPL2@@YAXPEAUactionargs_t@@@Z)
5>d_dehtbl.obj : error LNK2001: unresolved external symbol "void __cdecl A_FireGoldWandPL2(struct actionargs_t *)" (?A_FireGoldWandPL2@@YAXPEAUactionargs_t@@@Z)
5>d_dehtbl.obj : error LNK2001: unresolved external symbol "void __cdecl A_FireSkullRodPL1(struct actionargs_t *)" (?A_FireSkullRodPL1@@YAXPEAUactionargs_t@@@Z)
5>d_dehtbl.obj : error LNK2001: unresolved external symbol "void __cdecl A_ShutdownPhoenixPL2(struct actionargs_t *)" (?A_ShutdownPhoenixPL2@@YAXPEAUactionargs_t@@@Z)
5>d_dehtbl.obj : error LNK2001: unresolved external symbol "void __cdecl A_FireMacePL2(struct actionargs_t *)" (?A_FireMacePL2@@YAXPEAUactionargs_t@@@Z)
5>d_dehtbl.obj : error LNK2001: unresolved external symbol "void __cdecl A_FirePhoenixPL2(struct actionargs_t *)" (?A_FirePhoenixPL2@@YAXPEAUactionargs_t@@@Z)
5>d_dehtbl.obj : error LNK2001: unresolved external symbol "void __cdecl A_LoadShotgun2(struct actionargs_t *)" (?A_LoadShotgun2@@YAXPEAUactionargs_t@@@Z)
5>d_dehtbl.obj : error LNK2001: unresolved external symbol "void __cdecl A_FirePhoenixPL1(struct actionargs_t *)" (?A_FirePhoenixPL1@@YAXPEAUactionargs_t@@@Z)
5>d_dehtbl.obj : error LNK2001: unresolved external symbol "void __cdecl A_BFGsound(struct actionargs_t *)" (?A_BFGsound@@YAXPEAUactionargs_t@@@Z)
5>d_dehtbl.obj : error LNK2001: unresolved external symbol "void __cdecl A_HticSpawnFireBomb(struct actionargs_t *)" (?A_HticSpawnFireBomb@@YAXPEAUactionargs_t@@@Z)
5>d_dehtbl.obj : error LNK2001: unresolved external symbol "void __cdecl A_FireCrossbowPL2(struct actionargs_t *)" (?A_FireCrossbowPL2@@YAXPEAUactionargs_t@@@Z)
5>d_dehtbl.obj : error LNK2001: unresolved external symbol "void __cdecl A_FireCrossbowPL1(struct actionargs_t *)" (?A_FireCrossbowPL1@@YAXPEAUactionargs_t@@@Z)
5>d_dehtbl.obj : error LNK2001: unresolved external symbol "void __cdecl A_GauntletAttack(struct actionargs_t *)" (?A_GauntletAttack@@YAXPEAUactionargs_t@@@Z)
5>d_dehtbl.obj : error LNK2001: unresolved external symbol "void __cdecl A_BoltSpark(struct actionargs_t *)" (?A_BoltSpark@@YAXPEAUactionargs_t@@@Z)
5>d_dehtbl.obj : error LNK2001: unresolved external symbol "void __cdecl A_HticArtiTele(struct actionargs_t *)" (?A_HticArtiTele@@YAXPEAUactionargs_t@@@Z)
5>d_dehtbl.obj : error LNK2001: unresolved external symbol "void __cdecl A_InitPhoenixPL2(struct actionargs_t *)" (?A_InitPhoenixPL2@@YAXPEAUactionargs_t@@@Z)
5>d_dehtbl.obj : error LNK2001: unresolved external symbol "void __cdecl A_FireGoldWandPL1(struct actionargs_t *)" (?A_FireGoldWandPL1@@YAXPEAUactionargs_t@@@Z)
5>d_dehtbl.obj : error LNK2001: unresolved external symbol "void __cdecl A_OpenShotgun2(struct actionargs_t *)" (?A_OpenShotgun2@@YAXPEAUactionargs_t@@@Z)
5>d_dehtbl.obj : error LNK2001: unresolved external symbol "void __cdecl A_FireBlasterPL1(struct actionargs_t *)" (?A_FireBlasterPL1@@YAXPEAUactionargs_t@@@Z)
5>d_dehtbl.obj : error LNK2001: unresolved external symbol "void __cdecl A_DeathBallImpact(struct actionargs_t *)" (?A_DeathBallImpact@@YAXPEAUactionargs_t@@@Z)
5>d_dehtbl.obj : error LNK2001: unresolved external symbol "void __cdecl A_MacePL1Check(struct actionargs_t *)" (?A_MacePL1Check@@YAXPEAUactionargs_t@@@Z)
5>d_dehtbl.obj : error LNK2001: unresolved external symbol "void __cdecl A_StaffAttackPL1(struct actionargs_t *)" (?A_StaffAttackPL1@@YAXPEAUactionargs_t@@@Z)
5>d_dehtbl.obj : error LNK2001: unresolved external symbol "void __cdecl A_FireMacePL1(struct actionargs_t *)" (?A_FireMacePL1@@YAXPEAUactionargs_t@@@Z)
5>d_dehtbl.obj : error LNK2001: unresolved external symbol "void __cdecl A_MaceBallImpact2(struct actionargs_t *)" (?A_MaceBallImpact2@@YAXPEAUactionargs_t@@@Z)
5>d_dehtbl.obj : error LNK2001: unresolved external symbol "void __cdecl A_MaceBallImpact(struct actionargs_t *)" (?A_MaceBallImpact@@YAXPEAUactionargs_t@@@Z)
5>C:\Users\quidd\Desktop\AutoDoom-AutoDoom\vc2017\x64\Release\Eternity.exe : fatal error LNK1120: 42 unresolved externals
5>Done building project "Eternity.vcxproj" -- FAILED.
========== Build: 4 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========

**Comment by ioan-chera** [comment]
This is because I haven't been working on AutoDoom while on Windows lately. For this reason, I'm going to update CMakeLists.txt to create the Visual Studio project dynamically, then remove all the prebuilt projects.

**Comment by Quiddy85** [comment]
What are the steps to build this on Ubuntu? I really want to try the updated version. I followed the instructions for cmake, but didn't work

I don't want you to stop making it work on Windows, that's my main os. I just can't wait to look at the features since April.
Keep up the great work

Quiddy85

**Comment by ioan-chera** [comment]
CMake doesn't work as instructed? Not good. In any case, I plan to make CMakeLists.txt universal for all systems.

**Comment by Quiddy85** [comment]
Hold The Phone!!! I just downloaded to source today, ran it though CMake for windows and built it though VC2017. It seems to be working. I have the bot running though episode 1 now

It just came to me. The reason CMake wasn't working was that I was trying to use CMakeLists.txt from the source folder not the root folder.
I'm really sorry to waste your time on this.

Quiddy85
